### ISSUE TITLE
libpython3.8.dylib does not exist

### ISSUE THREAD

**Issue by tdhopper** [EconoBen/headsdown#2]
I got this error on the `setup.py` command. I have Python installed with pyenv. [It appears](https://github.com/visini/pomodoro/issues/1) that you have to install the python version with `PYTHON_CONFIGURE_OPTS="--enable-framework"` for this to work. 

```Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    setup(
  File "/Users/tim.hopper/repos/headsdown/.direnv/python-3.8.7/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/Users/tim.hopper/.pyenv/versions/3.8.7/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/tim.hopper/.pyenv/versions/3.8.7/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/tim.hopper/.pyenv/versions/3.8.7/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/tim.hopper/repos/headsdown/.direnv/python-3.8.7/lib/python3.8/site-packages/py2app/build_app.py", line 925, in run
    self._run()
  File "/Users/tim.hopper/repos/headsdown/.direnv/python-3.8.7/lib/python3.8/site-packages/py2app/build_app.py", line 1147, in _run
    self.run_normal()
  File "/Users/tim.hopper/repos/headsdown/.direnv/python-3.8.7/lib/python3.8/site-packages/py2app/build_app.py", line 1260, in run_normal
    self.create_binaries(py_files, pkgdirs, extensions, loader_files)
  File "/Users/tim.hopper/repos/headsdown/.direnv/python-3.8.7/lib/python3.8/site-packages/py2app/build_app.py", line 1644, in create_binaries
    mm.mm.run_file(runtime)
  File "/Users/tim.hopper/repos/headsdown/.direnv/python-3.8.7/lib/python3.8/site-packages/macholib/MachOGraph.py", line 89, in run_file
    raise ValueError("%r does not exist" % (pathname,))
ValueError: '/Users/tim.hopper/.pyenv/versions/3.8.7/lib/libpython3.8.dylib' does not exist```

**Comment by EconoBen** [comment]
This one I have seen before. The solution is as follows: 

`ln -s PATH/TO/FILE/libpython3.8m.dylib PATH/TO/FILE/libpython3.8.dylib`

it doesn't like the "m" in it. if you run line it creates an alias to the proper file I believe.
